exclude_shooters:
  surnames:
    - "(?i)^par$"
  ids: []

mark_chrono_failure_as_dnf: true

maps:
  division_code:
    "CPI.*": CPI
    "FSI.*": FSI
    "LCI.*": LCI
    "REV.*": REV
    "CPO.*": CPO
    "FSO.*": FSO
    "LCO.*": LCO
  category_code_map:
    "Junior.*": JUNIOR
    "Senior.*": SENIOR
    "Super Senior.*": SUPER SENIOR
    "Lady.*": LADY
    "International.*": INTERNATIONAL
    "Industry.*": INDUSTRY
    "Law Enforcement.*": LAW ENFORCEMENT
    "Military.*": MILITARY
    "Veteran.*": VETERAN
  class_code_map:
    "Double Platinum.*": DOUBLE PLATINUM
    "Platinum.*": PLATINUM
    "Gold.*": GOLD
    "Silver.*": SILVER
    "Bronze.*": BRONZE
    "Pew Pewter.*": PEW PEWTER
  division_place:
    1: CHAMPION
    2: 2nd PLACE
    3: 3rd PLACE

series:
  best_in_division:
    type: best_shooter
    group_by:
      - division
    filters:
      divisions:
        exclude:
          - "NFC.*"
    min_competitors: [1, 6, 11]
    exclude_dq: true
    exclude_dnf: true
    ineligible_penalties: []
    text:
      first_line: "{{ division_code(division) }} DIVISION"
      second_line: "{{ division_place(place) }}"

  most_accurate_iron_sight:
    type: most_accurate
    group_by: []
    filters:
      divisions:
        include:
          - "CPI.*"
          - "FSI.*"
          - "LCI.*"
          - "REV.*"
        exclude:
          - "NFC.*"
    min_competitors: [1]
    exclude_dq: true
    exclude_dnf: true
    ineligible_penalties:
      - "Hits on Non-Threat"
    text:
      first_line: "MOST ACCURATE"
      second_line: "IRON SIGHTS"
      third_line: "{{ shooter.points_down }} PD"

  most_accurate_optics:
    type: most_accurate
    group_by: []
    filters:
      divisions:
        include:
          - "CPO.*"
          - "FSO.*"
          - "LCO.*"
        exclude:
          - "NFC.*"
    min_competitors: [1]
    exclude_dq: true
    exclude_dnf: true
    ineligible_penalties:
      - "Hits on Non-Threat"
    text:
      first_line: "MOST ACCURATE"
      second_line: "OPTICS"
      third_line: "{{ shooter.points_down }} PD"

  best_lady:
    type: best_shooter
    group_by:
      - category
    filters:
      divisions:
        exclude:
          - "NFC.*"
      categories:
        include:
          - "Lady.*"
        exclude: []
    min_competitors: [1, 6, 11]
    exclude_dq: true
    exclude_dnf: true
    ineligible_penalties: []
    text:
      first_line: "HIGH"
      second_line: "{{ category_code_map(category) }}"

  best_in_category:
    type: best_shooter
    group_by:
      - category
    filters:
      divisions:
        exclude:
          - "NFC.*"
      categories:
        exclude:
          - "Lady.*"
    min_competitors: [1, 6, 11]
    exclude_dq: true
    exclude_dnf: true
    ineligible_penalties: []
    text:
      first_line: "HIGH"
      second_line: "{{ category_code_map(category) }}"

  fastest:
    type: fastest
    group_by: []
    filters:
      divisions:
        exclude:
          - "NFC.*"
    min_competitors: [1]
    exclude_dq: true
    exclude_dnf: true
    ineligible_penalties: []
    text:
      first_line: "FASTEST"
      second_line: "OVERALL"
      third_line: "{{ shooter.raw_time }} s"
